trigger:
  branches:
    include:
    - master
    - troy/*

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g snyk
    npm install -g snyk-to-html
  displayName: 'Install Snyk'

- script: |
    snyk auth $(SNYK_TOKEN)
    snyk code test
  displayName: 'Snyk Code Test'
