trigger:
  branches:
    include:
    - master
    - troy/*

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g snyk
    npm install -g snyk-to-html
  displayName: 'Install Snyk'

- script: |
    snyk auth $(SNYK_TOKEN)
    snyk code test --severity --json | snyk-to-html -o results.html
  displayName: 'Snyk Code Test'

- publish: $(System.DefaultWorkingDirectory)/results.html
  artifact: SAST_Results
  displayName: 'Publish Results'